# Generated by Django 3.0.8 on 2020-07-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='tel',
            field=models.CharField(default='', max_length=50),
        ),
    ]
