# Generated by Django 3.0.8 on 2020-07-25 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_countries_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='tel',
        ),
    ]
